<?xml version="1.0"?>
<package format="3">
  <name>rm_buff_tracker</name>
  <version>2.1.0</version>
  <description>RM energy mechanism tracker with ROS 2 support</description>
  <maintainer email="thekfjie@qq.com">Kfjie</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
