%YAML:1.0
pythonRoot: "../.."
parameterPath: "examples/example_for_prediction/10_dark_red_small_near/parameter.yaml"
videoPath: ""
color: "red"
mode: "small"
freq: 50
deltaT: 0.2
imshow: 1
detector: "hsv"
onnxModelPath: ""
yoloRelockIntervalFrames: 3
yoloRelockAfterMisses: 1
tune: 1
tuneFrame: -1
tunePreviewSpeed: 1.0
rBox: []
fanBox: []
