%YAML:1.0
pythonRoot: "../.."
parameterPath: "examples/example_for_prediction/6_dark_blue_big/parameter.yaml"
videoPath: ""
color: "blue"
mode: "big"
freq: 50
deltaT: 0.2
imshow: 1
detector: "yolo"
onnxModelPath: "../models/best.onnx"
yoloRelockIntervalFrames: 3
yoloRelockAfterMisses: 1
tune: 0
tuneFrame: -1
tunePreviewSpeed: 1.0
rBox: []
fanBox: []
